version: '3.8'

services:
  sukrtya-alpine-17-arm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: public.ecr.aws/docker/library/amazoncorretto:17-alpine3.21
      platforms:
        - linux/arm64
      # target: builder
    image: sukrtya-alpine-17:latest

  sukrtya-alpine-8-arm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: public.ecr.aws/docker/library/amazoncorretto:8-alpine3.21
      platforms:
        - linux/arm64
      # target: builder
    image: sukrtya-alpine-8:latest