services:
  your-app:
    image: egov-mdms-service
    volumes:
      - /Users/chandan/Projects/mdms-data/data:/app/data
    environment:
      - egov.mdms.conf.path=/app/data
    ports:
      - "8094:8094"